//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_BEHAVIOUR_TAB               101
#define IDD_CONFIG_NAME                 102
#define IDD_CONFIG_TABS                 103
#define IDD_CONTROLS_TAB                104
#define IDD_COVER_DISPLAY_TAB           105
#define IDD_DISPLAY_TAB                 106
#define IDD_PERF_TAB                    107
#define IDD_SOURCE_TAB                  108
#define IDB_SPINNER                     109
#define IDD_CONTEXT_MENU_TAB            109
#define IDB_COVER_LOADING_PNG           110
#define IDB_COVER_NO_IMG_PNG            112
#define IDR_COVER_LOADING               200
#define IDR_COVER_NO_IMG                203
#define IDR_COVER_LOADING_DARK          204
#define IDC_ALBUM_FORMAT                1001
#define IDC_ALBUM_TITLE                 1002
#define IDC_APPLY_TITLE                 1003
#define IDC_BG_COLOR                    1004
#define IDC_BG_COLOR_CUSTOM             1005
#define IDC_BG_COLOR_PREV               1006
#define IDC_BTN_REFRESH                 1007
#define IDC_CACHE_SIZE                  1008
#define IDC_CACHE_SIZE_SPIN             1009
#define IDC_CHECK_BEHA_ACTFLAG_D_HIGHLIGHT 1010
#define IDC_CHECK_BEHA_ACTFLAG_D_PLAY   1011
#define IDC_CHECK_BEHA_ACTFLAG_D_QUEUE  1012
#define IDC_CHECK_BEHA_ACTFLAG_D_RATED  1013
#define IDC_CHECK_BEHA_ACTFLAG_D_RATED_HIGHT 1014
#define IDC_CHECK_BEHA_ACTFLAG_D_SET    1015
#define IDC_CHECK_BEHA_ACTFLAG_E_HIGHLIGHT 1016
#define IDC_CHECK_BEHA_ACTFLAG_E_PLAY   1017
#define IDC_CHECK_BEHA_ACTFLAG_E_QUEUE  1018
#define IDC_CHECK_BEHA_ACTFLAG_E_RATED  1019
#define IDC_CHECK_BEHA_ACTFLAG_E_RATED_HIGHT 1020
#define IDC_CHECK_BEHA_ACTFLAG_E_SET    1021
#define IDC_CHECK_BEHA_ACTFLAG_M_HIGHLIGHT 1022
#define IDC_CHECK_BEHA_ACTFLAG_M_PLAY   1023
#define IDC_CHECK_BEHA_ACTFLAG_M_QUEUE  1024
#define IDC_CHECK_BEHA_ACTFLAG_M_RATED  1025
#define IDC_CHECK_BEHA_ACTFLAG_M_RATED_HIGHT 1026
#define IDC_CHECK_BEHA_ACTFLAG_M_SET    1027
#define IDC_CHECK_BEHA_COVER_FOLLOWS_ANONYM 1028
#define IDC_CHECK_BEHA_COVER_FOLLOWS_LIBRARY 1029
#define IDC_CHECK_BEHA_COVER_FOLLOWS_PLAYLIST 1030
#define IDC_COMBO_BEHA_ADD_REPLACE_FLAG_D 1031
#define IDC_COMBO_BEHA_ADD_REPLACE_FLAG_E 1032
#define IDC_COMBO_BEHA_ADD_REPLACE_FLAG_M 1033
#define IDC_COMPILE                     1034
#define IDC_COMPILE_STATUS              1035
#define IDC_CONFIG_NAME                 1036
#define IDC_CONTROLS_EDIT_DOCU          1037
#define IDC_COVER_ART_PNG8_ALPHA        1038
#define IDC_DISPLAY_CONFIG              1039
#define IDC_DOUBLE_CLICK                1040
#define IDC_EDIT_BEHA_HRATE             1041
#define IDC_EMPTY_ON_MINIMIZE           1042
#define IDC_ENTER_KEY                   1043
#define IDC_FILTER                      1044
#define IDC_FIND_AS_YOU_TYPE            1045
#define IDC_FIND_AS_YOU_TYPE_CS         1046
#define IDC_FOLLOW_DELAY                1047
#define IDC_FOLLOW_DELAY_SPINNER        1048
#define IDC_FOLLOW_PLAYBACK             1049
#define IDC_FONT                        1050
#define IDC_FONT_CUSTOM                 1051
#define IDC_FONT_PREV                   1052
#define IDC_FRAME_WIDTH                 1053
#define IDC_FRAME_WIDTH_SPIN            1054
#define IDC_GROUP                       1055
#define IDC_GROUP_FIND_AS_YOU_TYPE      1056
#define IDC_GROUP_FOLLOW_PLAYBACK       1057
#define IDC_HIDDEN_CUSTOM_ACTION_FLAG   1058
#define IDC_HIDDEN_DISPLAY_CUSTOM_COVER_ART 1059
#define IDC_HIDDEN_LOGFONT              1061
#define IDC_HIDDEN_PANELBG_CUSTOM       1062
#define IDC_HIDDEN_TITLE_COLOR_CUSTOM   1063
#define IDC_HIDDEN_VSYNC_MODE           1064
#define IDC_IMG_LOADING                 1065
#define IDC_IMG_LOADING_BROWSE          1066
#define IDC_IMG_NO_COVER                1067
#define IDC_IMG_NO_COVER_BROWSE         1068
#define IDC_INNER_SORT                  1069
#define IDC_MIDDLE_CLICK                1070
#define IDC_MULTI_SAMPLING              1071
#define IDC_MULTI_SAMPLING_PASSES       1072
#define IDC_PANEL_DISPLAY_COMBO_CUSTOM_COVER_ART 1073
#define IDC_SAVED_ADD                   1074
#define IDC_SAVED_REMOVE                1075
#define IDC_SAVED_RENAME                1076
#define IDC_SAVED_SELECT                1077
#define IDC_SHOW_FPS                    1078
#define IDC_SORT                        1079
#define IDC_SORT_GROUP                  1080
#define IDC_SOURCE_FROM_ACTIVE_PLAYLIST 1081
#define IDC_SOURCE_FROM_LIBRARY_SELECTOR 1082
#define IDC_SOURCE_FROM_LIBRARY_SELECTOR_LOCK 1083
#define IDC_SOURCE_FROM_PLAYLIST        1084
#define IDC_SOURCE_PLAYLIST_GROUP       1086
#define IDC_SOURCE_PLAYLIST_NAME        1087
#define IDC_SPIN_BEHA_HRATE             1088
#define IDC_STATICD_FOLLOW_PLAYBACK_DESC 1089
#define IDC_STATIC_BEHA_ACTFLAG_LABEL_BOTTOM 1090
#define IDC_SOURCE_HIDE_EXP6            1090
#define IDC_STATIC_BEHA_HRATE           1091
#define IDC_STATIC_EXP_SRC              1092
#define IDC_STATIC_FIND_AS_YOU_TYPE_DESC 1093
#define IDC_STATIC_FOLLOW_DELAY_WAIT    1094
#define IDC_STATIC_GROUP_BEHA_RATING    1095
#define IDC_STATIC_CUSTOM_COVER_ART     1096
#define IDC_STATIC_SRC_PL_NAME          1097
#define IDC_TABS                        1098
#define IDC_TARGET_PL                   1099
#define IDC_TEXTCOLOR                   1100
#define IDC_TEXTCOLOR_CUSTOM            1101
#define IDC_TEXTCOLOR_PREV              1102
#define IDC_TEXTURE_COMPRESSION         1103
#define IDC_TEXTURE_SIZE                1104
#define IDC_TEXTURE_SIZE_SPIN           1105
#define IDC_TITLE_PREVIEW               1106
#define IDC_TPOS_H                      1107
#define IDC_TPOS_H_P                    1108
#define IDC_TPOS_V                      1109
#define IDC_TPOS_V_P                    1110
#define IDC_VSYNC_OFF                   1111
#define IDC_VSYNC_ONLY                  1112
#define IDC_VSYNC_SLEEP                 1113
#define IDC_EDIT1                       1114
#define IDC_HIDDEN_TPOS_V               1114
#define IDC_SOURCE_PLAYLIST_NGTITLE     1114
#define IDC_KK                          1114
#define IDC_HIDDEN_SAVED_SELECT         1114
#define IDC_EDIT2                       1115
#define IDC_HIDDEN_TPOS_H               1115
#define IDC_STATIC_VSYNC                1116
#define IDC_STATIC_BENCH                1117
#define IDC_STATIC_WARNING              1118
#define IDC_STATIC_ALBUM                1119
#define IDC_STATIC_VERTICAL             1120
#define IDC_STATIC_HORIZONTAL           1121
#define IDC_STATIC_PDISPLAY             1122
#define IDC_STATIC_GROUPBY              1123
#define IDC_STATIC_SORTBY               1124
#define IDC_STATIC_NOCOVER              1125
#define IDC_STATIC_COVERLOADING         1126
#define IDC_STATIC_SORTWALBUM           1127
#define IDC_STATIC_POSITION             1128
#define IDC_STATIC_PERCENT              1129
#define IDC_STATIC_PERCENT_VIS          1130
#define IDC_STATIC_COLOR                1131
#define IDC_STATIC_FONT                 1132
#define IDC_STATIC_BACKCOLOR            1133
#define IDC_STATIC_PREVIEW              1134
#define IDC_STATIC_ALBUMFRAME           1135
#define IDC_STATIC_HFW                  1136
#define IDC_STATIC_NFAYT                1137
#define IDC_STATIC_ACTIONS              1138
#define IDC_STATIC_DEFPLAYLIST          1139
#define IDC_STATIC_DCLICK               1140
#define IDC_STATIC_DCLICK_VIS           1141
#define IDC_STATIC_MCLICK               1142
#define IDC_STATIC_MCLICK_VIS           1143
#define IDC_STATIC_ENTER                1144
#define IDC_STATIC_ENTER_VIS            1145
#define IDC_STATIC_NRR                  1146
#define IDC_STATIC_TEXTUREC             1147
#define IDC_STATIC_TEXTURESZ            1148
#define IDC_STATIC_TEXTUREMSZ           1149
#define IDC_STATIC_NRHP                 1150
#define IDC_STATIC_SPECIAL_ART          1151
#define IDC_CHECK1                      1152
#define IDC_COVER_DISPLAY_LEGACY_EXTVIEWER 1152
#define IDC_CHECK_HOLDER_PLS_SET_SEL    1152
#define IDC_STATIC_SRC_PL_NGTITLE       1153
#define IDC_COMBO_SOURCE_PLAYLIST_NAME  1154
#define IDC_STATIC_LIB_BRW_SRC          1155
#define IDC_CHECK_BEHA_COVER_HIGHLIGHT_PLAYLIST 1156
#define IDC_CTX_SOURCE_HIDE             1157
#define IDC_CTX_DISPLAY_HIDE            1158
#define IDC_CTX_SELECTOR_HIDE           1159
#define IDC_CTX_EXTERNALVIEWER_HIDE     1160
#define IDC_CTX_CUSTOMACTIONS_HIDE      1161

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
